server:
  port: 8000


spring:
  application:
    name: siy-api-gateway
  redis:
    host: localhost
    port: 6379
  cache:
    cache-names: tokenCache
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allow-credentials: true
      routes:
        - id: siy-user-service
          uri: lb://SIY-USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: siy-user-service
          uri: lb://SIY-USER-SERVICE
          predicates:
            - Path=/user-service/signup
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: siy-user-service
          uri: lb://SIY-USER-SERVICE
          predicates:
            - Path=/user-service/refresh
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - RefreshTokenFilter
        - id: siy-user-service
          uri: lb://SIY-USER-SERVICE
          predicates:
            - Path=/user-service/logout
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - LogOutFilter
        - id: siy-user-service
          uri: lb://SIY-USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: siy-user-service
          uri: lb://SIY-USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationCookieFilter
        - id: siy-post-service
          uri: lb://SIY-POST-SERVICE
          predicates:
            - Path=/post-service/**
          filters:
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}
            - AuthorizationCookieFilter
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace,busrefresh, info, prometheus, metrics
